language: node_js
node_js:
    - "6"
    - "7"
    - "8"
services:
    - mysql
    - redis-server
before_install:
    - mysql -e 'CREATE DATABASE janusvr;'
    - cp test/test-config.js ./config.js
    - ./generate_key_ni

